export const GET_CURRENT_LOCATION_WEATHER = "GET_CURRENT_LOCATION_WEATHER";
export const GET_WEATHER = "GET_WEATHER";
export const SET_THEME_LIGHT = "SET_THEME_LIGHT";
export const SET_THEME_DARK = "SET_THEME_DARK";